[project]
name = "mlops-lab1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "kristytannoury", email = "christietannoury7@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "mlflow>=3.16.0",
    "pillow>=12.3.0",
    "scikit-learn>=1.9.1",
    "torch>=2.14.0",
    "torchvision>=0.29.0",
]

[project.scripts]
mlops-lab1 = "mlops_lab1:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
